version: "3"
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: "postgresdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
#      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
#    volumes:
#      - /home/RiderProjects/TrainList/DB:/var/lib/postgresql/data

